// SAMPLE ONLY: work/drafts/lenses.json does not exist yet. Generated by work/tools/integrate.py
// from the chapters so the site's lenses machinery can be built and tested.
window.LENSES_SAMPLE = true;
window.LENSES = {
 "ch1": {
  "money": {
   "notes": [
    {
     "para_index": 4,
     "para_start": "On July 1, 1985, InterNorth bought HNG. It",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 15,
     "para_start": "On paper, the growth was dramatic. Enron's reported",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "auditors": {
   "notes": [
    {
     "para_index": 9,
     "para_start": "Arthur Andersen, which had audited InterNorth, became the",
     "text": "[Sample note] Layout test text for the auditors lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "board": {
   "notes": [],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "knew": {
   "notes": [],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here.",
   "strip": [
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ]
  }
 },
 "ch2": {
  "money": {
   "notes": [
    {
     "para_index": 5,
     "para_start": "Enron's reported revenue rose from $13.3 billion in",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 13,
     "para_start": "Enron applied the same idea to stakes it",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 17,
     "para_start": "The committee found that Enron's management therefore preferred",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "auditors": {
   "notes": [
    {
     "para_index": 11,
     "para_start": "Enron's own accounting policy, printed in its 2000",
     "text": "[Sample note] Layout test text for the auditors lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "board": {
   "notes": [
    {
     "para_index": 17,
     "para_start": "The committee found that Enron's management therefore preferred",
     "text": "[Sample note] Layout test text for the board lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "knew": {
   "notes": [
    {
     "para_index": 12,
     "para_start": "Enron had checked with its regulator first. The",
     "text": "[Sample note] Layout test text for the knew lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here.",
   "strip": [
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ]
  }
 },
 "ch3": {
  "money": {
   "notes": [
    {
     "para_index": 4,
     "para_start": "In 1993, Enron and the California Public Employees'",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 8,
     "para_start": "Kopper was paid about $2 million in fees",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 13,
     "para_start": "Chapter 2 introduced Enron's stake in Rhythms NetConnections.",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 16,
     "para_start": "When the Rhythms deal was unwound in 2000,",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 19,
     "para_start": "In the last two quarters of 2000, $532",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "auditors": {
   "notes": [
    {
     "para_index": 18,
     "para_start": "In the first Raptor, created in April 2000,",
     "text": "[Sample note] Layout test text for the auditors lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "board": {
   "notes": [
    {
     "para_index": 5,
     "para_start": "In 1997, Enron needed a new partner to",
     "text": "[Sample note] Layout test text for the board lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 9,
     "para_start": "On June 28, 1999, the board approved a",
     "text": "[Sample note] Layout test text for the board lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 20,
     "para_start": "By December 2000, two Raptors lacked the money",
     "text": "[Sample note] Layout test text for the board lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "knew": {
   "notes": [
    {
     "para_index": 6,
     "para_start": "On November 5, 1997, the board's Executive Committee",
     "text": "[Sample note] Layout test text for the knew lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 15,
     "para_start": "The special committee explained the problem: \"The normal",
     "text": "[Sample note] Layout test text for the knew lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 23,
     "para_start": "Enron's public filings did mention the LJM partnerships.",
     "text": "[Sample note] Layout test text for the knew lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here.",
   "strip": [
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ]
  }
 },
 "ch4": {
  "money": {
   "notes": [
    {
     "para_index": 11,
     "para_start": "On August 22, 2001, Watkins met Lay in",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "auditors": {
   "notes": [
    {
     "para_index": 2,
     "para_start": "In February 1999, Arthur Andersen's lead partner on",
     "text": "[Sample note] Layout test text for the auditors lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 6,
     "para_start": "In early 2001, the examiner reported, Carl Bass,",
     "text": "[Sample note] Layout test text for the auditors lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "board": {
   "notes": [
    {
     "para_index": 2,
     "para_start": "In February 1999, Arthur Andersen's lead partner on",
     "text": "[Sample note] Layout test text for the board lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 15,
     "para_start": "Meanwhile, the Raptors were being shut down. The",
     "text": "[Sample note] Layout test text for the board lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "knew": {
   "notes": [
    {
     "para_index": 3,
     "para_start": "What the directors took from such discussions is",
     "text": "[Sample note] Layout test text for the knew lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 5,
     "para_start": "On February 5, 2001, senior Andersen partners held",
     "text": "[Sample note] Layout test text for the knew lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 10,
     "para_start": "Watkins testified that on August 15, 2001, the",
     "text": "[Sample note] Layout test text for the knew lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 13,
     "para_start": "Watkins was not the only source of concern",
     "text": "[Sample note] Layout test text for the knew lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 16,
     "para_start": "Outside Enron, the SEC reviews companies' annual reports",
     "text": "[Sample note] Layout test text for the knew lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here.",
   "strip": [
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ]
  }
 },
 "ch5": {
  "money": {
   "notes": [
    {
     "para_index": 1,
     "para_start": "On October 16, 2001, Enron announced its results",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 3,
     "para_start": "On the same day, in a conference call",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 7,
     "para_start": "Enron's credit was now in danger. Enron said",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 9,
     "para_start": "Enron's quarterly report, filed November 19, gave refined",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 12,
     "para_start": "The quarterly report Enron filed on November 19",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 15,
     "para_start": "On November 28, all three major credit rating",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 17,
     "para_start": "The New York Stock Exchange suspended trading in",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "auditors": {
   "notes": [
    {
     "para_index": 3,
     "para_start": "On the same day, in a conference call",
     "text": "[Sample note] Layout test text for the auditors lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "board": {
   "notes": [],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "knew": {
   "notes": [
    {
     "para_index": 5,
     "para_start": "On October 17, the SEC asked Enron to",
     "text": "[Sample note] Layout test text for the knew lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 13,
     "para_start": "That same day, at a meeting with its",
     "text": "[Sample note] Layout test text for the knew lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 18,
     "para_start": "The court-appointed bankruptcy examiner wrote that the disclosures",
     "text": "[Sample note] Layout test text for the knew lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here.",
   "strip": [
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ]
  }
 },
 "ch6": {
  "money": {
   "notes": [
    {
     "para_index": 4,
     "para_start": "Enron was one of Andersen's most important clients",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "auditors": {
   "notes": [
    {
     "para_index": 2,
     "para_start": "Arthur Andersen, which had audited InterNorth, became the",
     "text": "[Sample note] Layout test text for the auditors lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 4,
     "para_start": "Enron was one of Andersen's most important clients",
     "text": "[Sample note] Layout test text for the auditors lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 6,
     "para_start": "According to the bankruptcy examiner, Andersen accountants later",
     "text": "[Sample note] Layout test text for the auditors lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 8,
     "para_start": "The examiner also concluded that a fact-finder could",
     "text": "[Sample note] Layout test text for the auditors lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 10,
     "para_start": "Nancy Temple, a lawyer at Andersen, testified that",
     "text": "[Sample note] Layout test text for the auditors lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 12,
     "para_start": "Duncan's account, as a House subcommittee chairman summarized",
     "text": "[Sample note] Layout test text for the auditors lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 14,
     "para_start": "Andersen reported the destruction to the Justice Department",
     "text": "[Sample note] Layout test text for the auditors lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 16,
     "para_start": "The firm did not survive as an operating",
     "text": "[Sample note] Layout test text for the auditors lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 18,
     "para_start": "Duncan faced cases of his own. According to",
     "text": "[Sample note] Layout test text for the auditors lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "board": {
   "notes": [
    {
     "para_index": 8,
     "para_start": "The examiner also concluded that a fact-finder could",
     "text": "[Sample note] Layout test text for the board lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "knew": {
   "notes": [
    {
     "para_index": 7,
     "para_start": "The examiner found evidence that \"Enron officers withheld",
     "text": "[Sample note] Layout test text for the knew lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 11,
     "para_start": "On October 17, the SEC asked Enron for",
     "text": "[Sample note] Layout test text for the knew lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here.",
   "strip": [
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ]
  }
 },
 "ch7": {
  "money": {
   "notes": [
    {
     "para_index": 3,
     "para_start": "The subcommittee also found that the board failed",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 10,
     "para_start": "Banks faced civil cases. In 2003, without admitting",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 12,
     "para_start": "In the fall of 2001, as the stock",
     "text": "[Sample note] Layout test text for the money lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "auditors": {
   "notes": [],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "board": {
   "notes": [
    {
     "para_index": 1,
     "para_start": "Several bodies investigated what went wrong, and their",
     "text": "[Sample note] Layout test text for the board lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "para_index": 3,
     "para_start": "The subcommittee also found that the board failed",
     "text": "[Sample note] Layout test text for the board lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here."
  },
  "knew": {
   "notes": [
    {
     "para_index": 12,
     "para_start": "In the fall of 2001, as the stock",
     "text": "[Sample note] Layout test text for the knew lens on this paragraph. The real note is being written.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ],
   "summary": [
    "[Sample] First summary point for this lens.",
    "[Sample] Second summary point.",
    "[Sample] Third summary point."
   ],
   "ask_why": "[Sample] An open discussion question for this lens will appear here.",
   "strip": [
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    },
    {
     "date": "[date]",
     "who": "[Sample] person or body",
     "what": "[Sample] what the documents show they knew or were told.",
     "cites": [
      {
       "card": "SAMPLE",
       "source_id": "powers-report-sec",
       "page": null,
       "loc": "[sample locator]"
      }
     ]
    }
   ]
  }
 }
};
