// SAMPLE ONLY: work/drafts/pathways.json does not exist yet. Generated by work/tools/integrate.py
// from the chapters so the site's pathways machinery can be built and tested.
window.PATHWAYS_SAMPLE = true;
window.PATHWAYS = [
 {
  "id": "first-reading",
  "title": "A First Reading",
  "for_whom": "[Sample] who this pathway is for",
  "minutes": 45,
  "intro": "[Sample] Layout test text. The real introduction is being written.",
  "stops": [
   {
    "page": "chapters/ch1.html",
    "anchor": "",
    "label": "Chapter 1: Origins",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "chapters/ch2.html",
    "anchor": "what-mark-to-market-accounting-means",
    "label": "Chapter 2: mark-to-market",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "chapters/ch3.html?lens=money",
    "anchor": "the-raptors",
    "label": "Chapter 3: the Raptors, with the money lens",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "cast.html",
    "anchor": "sherron-watkins",
    "label": "Cast: Sherron Watkins",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "timeline.html",
    "anchor": "tl-2001-12-02",
    "label": "Timeline: December 2, 2001",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "footnote.html",
    "anchor": "fn-05",
    "label": "The Footnote, annotation 5",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "chapters/ch7.html",
    "anchor": "",
    "label": "Chapter 7",
    "bridge": "[Sample] What to notice at this stop."
   }
  ],
  "closing_question": "[Sample] A closing question will appear here.",
  "handout": {
   "questions": [
    "[Sample] Discussion question 1.",
    "[Sample] Discussion question 2.",
    "[Sample] Discussion question 3."
   ]
  }
 },
 {
  "id": "mark-to-market",
  "title": "Mark-to-Market Explained",
  "for_whom": "[Sample] who this pathway is for",
  "minutes": 25,
  "intro": "[Sample] Layout test text. The real introduction is being written.",
  "stops": [
   {
    "page": "glossary.html",
    "anchor": "mark-to-market",
    "label": "Glossary: mark-to-market",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "chapters/ch2.html",
    "anchor": "what-mark-to-market-accounting-means",
    "label": "Chapter 2",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "chapters/ch2.html?lens=money",
    "anchor": "marking-investments-to-market",
    "label": "Chapter 2, money lens",
    "bridge": "[Sample] What to notice at this stop."
   }
  ],
  "closing_question": "[Sample] A closing question will appear here.",
  "handout": {
   "questions": [
    "[Sample] Discussion question 1.",
    "[Sample] Discussion question 2.",
    "[Sample] Discussion question 3."
   ]
  }
 },
 {
  "id": "spes",
  "title": "The Special Purpose Entities",
  "for_whom": "[Sample] who this pathway is for",
  "minutes": 35,
  "intro": "[Sample] Layout test text. The real introduction is being written.",
  "stops": [
   {
    "page": "chapters/ch3.html",
    "anchor": "chewco",
    "label": "Chewco",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "chapters/ch3.html?lens=board",
    "anchor": "the-ljm-partnerships",
    "label": "LJM, board lens",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "cast.html",
    "anchor": "andrew-fastow",
    "label": "Cast: Andrew Fastow",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "footnote.html",
    "anchor": "fn-10",
    "label": "The Footnote",
    "bridge": "[Sample] What to notice at this stop."
   }
  ],
  "closing_question": "[Sample] A closing question will appear here.",
  "handout": {
   "questions": [
    "[Sample] Discussion question 1.",
    "[Sample] Discussion question 2.",
    "[Sample] Discussion question 3."
   ]
  }
 },
 {
  "id": "andersen",
  "title": "Andersen's Fall and the Big Five to Big Four",
  "for_whom": "[Sample] who this pathway is for",
  "minutes": 30,
  "intro": "[Sample] Layout test text. The real introduction is being written.",
  "stops": [
   {
    "page": "chapters/ch6.html?lens=auditors",
    "anchor": "enrons-auditor",
    "label": "Chapter 6, auditors lens",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "cast.html",
    "anchor": "david-duncan",
    "label": "Cast: David Duncan",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "timeline.html",
    "anchor": "tl-2005-05-31",
    "label": "Timeline: 2005",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "chapters/ch6.html",
    "anchor": "the-big-four",
    "label": "The Big Four",
    "bridge": "[Sample] What to notice at this stop."
   }
  ],
  "closing_question": "[Sample] A closing question will appear here.",
  "handout": {
   "questions": [
    "[Sample] Discussion question 1.",
    "[Sample] Discussion question 2.",
    "[Sample] Discussion question 3."
   ]
  }
 },
 {
  "id": "sox",
  "title": "From Enron to Sarbanes-Oxley and the PCAOB",
  "for_whom": "[Sample] who this pathway is for",
  "minutes": 30,
  "intro": "[Sample] Layout test text. The real introduction is being written.",
  "stops": [
   {
    "page": "chapters/ch7.html",
    "anchor": "",
    "label": "Chapter 7",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "timeline.html",
    "anchor": "tl-2002-07-30",
    "label": "Timeline: July 30, 2002",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "why-it-matters.html",
    "anchor": "s302",
    "label": "Section 302",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "why-it-matters.html",
    "anchor": "s404",
    "label": "Section 404",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "why-it-matters.html",
    "anchor": "pcaob",
    "label": "The PCAOB",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "why-it-matters.html",
    "anchor": "independence",
    "label": "Auditor independence",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "why-it-matters.html",
    "anchor": "whistleblowers",
    "label": "Whistleblowers",
    "bridge": "[Sample] What to notice at this stop."
   }
  ],
  "closing_question": "[Sample] A closing question will appear here.",
  "handout": {
   "questions": [
    "[Sample] Discussion question 1.",
    "[Sample] Discussion question 2.",
    "[Sample] Discussion question 3."
   ]
  }
 },
 {
  "id": "footnotes",
  "title": "Reading the Footnotes",
  "for_whom": "[Sample] who this pathway is for",
  "minutes": 30,
  "intro": "[Sample] Layout test text. The real introduction is being written.",
  "stops": [
   {
    "page": "footnote.html",
    "anchor": "fn-01",
    "label": "The Footnote",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "footnote.html",
    "anchor": "fn-20",
    "label": "Annotation 20",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "glossary.html",
    "anchor": "related-party-transaction",
    "label": "Glossary",
    "bridge": "[Sample] What to notice at this stop."
   }
  ],
  "closing_question": "[Sample] A closing question will appear here.",
  "handout": {
   "questions": [
    "[Sample] Discussion question 1.",
    "[Sample] Discussion question 2.",
    "[Sample] Discussion question 3."
   ]
  }
 },
 {
  "id": "banks",
  "title": "The Banks",
  "for_whom": "[Sample] who this pathway is for",
  "minutes": 30,
  "intro": "[Sample] Layout test text. The real introduction is being written.",
  "stops": [
   {
    "page": "banks.html",
    "anchor": "prepays",
    "label": "Prepays",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "banks.html",
    "anchor": "deals",
    "label": "The deals",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "cast.html",
    "anchor": "jpmorgan-citigroup",
    "label": "Cast: JPMorgan and Citigroup",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "banks.html",
    "anchor": "institutions",
    "label": "Institutions",
    "bridge": "[Sample] What to notice at this stop."
   },
   {
    "page": "banks.html",
    "anchor": "outcomes",
    "label": "Outcomes",
    "bridge": "[Sample] What to notice at this stop."
   }
  ],
  "closing_question": "[Sample] A closing question will appear here.",
  "handout": {
   "questions": [
    "[Sample] Discussion question 1.",
    "[Sample] Discussion question 2.",
    "[Sample] Discussion question 3."
   ]
  }
 }
];
