#!/usr/bin/env python3
"""Generate js/sources-data.js from sources/manifest.csv and sources/download_log.csv.

The website has no build step; this script is run by hand whenever the
manifest changes. It writes `window.SOURCES = {id: {...}}` so pages opened
from disk (file://) can load the source list with a plain <script> tag.
"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "sources" / "manifest.csv"
LOG = ROOT / "sources" / "download_log.csv"
OUT = ROOT / "js" / "sources-data.js"


def main():
    with LOG.open(newline="", encoding="utf-8") as f:
        log = {r["id"]: r for r in csv.DictReader(f)}
    sources = {}
    with MANIFEST.open(newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            entry = log.get(r["id"], {})
            fname = r["filename"]
            sources[r["id"]] = {
                "id": r["id"],
                "title": r["title"],
                "date": r["date"],
                "source_body": r["source_body"],
                "folder": r["folder"],
                "filename": fname,
                "url": r["url"],
                "status": r["status"],
                "sha256": entry.get("sha256", ""),
                "in_library": bool(entry.get("sha256")),
                "is_pdf": fname.lower().endswith(".pdf"),
            }
    body = json.dumps(sources, indent=1, ensure_ascii=False)
    OUT.write_text(
        "// GENERATED by work/tools/make_sources_js.py from sources/manifest.csv\n"
        "// and sources/download_log.csv. Do not edit by hand; re-run the script.\n"
        f"window.SOURCES = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)} with {len(sources)} sources")


if __name__ == "__main__":
    main()
