// Generated from images/credits.json. Keep the two files in sync.
window.IMAGE_CREDITS = [
  {
    "id": "enron-complex",
    "file": "images/enron-complex.jpg",
    "title": "The former Enron office complex, Houston, at night",
    "description": "Night view of the office towers in downtown Houston that the Commons file page identifies as the Enron complex. Photographed in March 2008, several years after Enron's collapse.",
    "alt": "Two curved glass office towers lit up at night, joined by a curved walkway, with a Smith Street sign in the foreground.",
    "source_url": "https://commons.wikimedia.org/wiki/File:Enron_Complex.jpg",
    "author": "Alex (Flickr user; originally posted to Flickr as \"Enron Complex\")",
    "license": "CC BY 2.0",
    "license_url": "https://creativecommons.org/licenses/by/2.0/",
    "is_original_diagram": false,
    "person_identified_by_source": null,
    "suggested_chapter": "1 Origins (alt: 5 Collapse)",
    "credit_line": "Photo: Alex, via Wikimedia Commons, CC BY 2.0",
    "retrieved": "2026-09-26",
    "sha256": "749981fbedcb0688ca4827c4705e61a45a37adaf81e0b81d427b13f775c5c2c9",
    "notes": "License confirmed by Flickr review bot on Commons (Aug 2008). Downloaded as 1280px Commons thumbnail."
  },
  {
    "id": "enron-logo-1997",
    "file": "images/enron-logo-1997.svg",
    "title": "Enron corporate logo",
    "description": "Enron's tilted-E logo. Commons gives its source as Enron's 2000 annual report (archived copy) and names the designer as Paul Rand.",
    "alt": "Enron logo: a tilted capital E in blue, green and red above the word Enron.",
    "source_url": "https://commons.wikimedia.org/wiki/File:Logo_of_Enron_Corporation_(1997).svg",
    "author": "Paul Rand (designer), per Wikimedia Commons",
    "license": "Public domain (text logo below the threshold of originality; may still be a trademark)",
    "license_url": "https://commons.wikimedia.org/wiki/Template:PD-textlogo",
    "is_original_diagram": false,
    "person_identified_by_source": null,
    "suggested_chapter": "1 Origins",
    "credit_line": "Enron logo, via Wikimedia Commons (public domain text logo; trademark)",
    "retrieved": "2026-09-26",
    "sha256": "4b0f04f13916cb057918b7e8b8e590d8ba91d933cbb22cc261111a5964afd11d",
    "notes": "Commons marks it PD-textlogo and 'trademarked'. Use it only to identify the company, not in a way that suggests endorsement. The date in the file name (1997) comes from Commons, not from the library; do not cite it as a fact. The 1986 logo on Commons is CC BY-SA 4.0 (a redrawing) and was not taken."
  },
  {
    "id": "gas-pipeline-station",
    "file": "images/gas-pipeline-station.jpg",
    "title": "A natural gas pipeline station",
    "description": "Above-ground pipes and valves at a small natural gas pipeline station on a university campus in Ohio (2020). A generic picture of gas pipeline equipment; not an Enron facility.",
    "alt": "Dark painted gas pipes, valves and meters rising out of a concrete pad inside a fenced enclosure.",
    "source_url": "https://commons.wikimedia.org/wiki/File:Natural_Gas_Pipeline_Station.jpg",
    "author": "Mbrickn",
    "license": "CC BY 4.0",
    "license_url": "https://creativecommons.org/licenses/by/4.0/",
    "is_original_diagram": false,
    "person_identified_by_source": null,
    "suggested_chapter": "2 Business model (secondary; prefer nyse-trading-floor)",
    "credit_line": "Photo: Mbrickn, via Wikimedia Commons, CC BY 4.0",
    "retrieved": "2026-09-26",
    "sha256": "8ba4c6cd73465c8ca0e7e2806e2e96a60eb5da41814bf7c770b4b37d3a6e8a20",
    "notes": "Modest image; caption must say it is generic, not Enron's. Downloaded as 1280px Commons thumbnail."
  },
  {
    "id": "nyse-trading-floor",
    "file": "images/nyse-trading-floor.jpg",
    "title": "A trading floor: the New York Stock Exchange",
    "description": "The trading floor of the New York Stock Exchange, photographed by Carol M. Highsmith (Library of Congress; dated only 'between 1980 and 2006'). Shown as a generic example of a trading floor. It is a stock exchange, not Enron's energy-trading floor.",
    "alt": "A crowded stock exchange floor seen from above, with trading booths full of screens and large NYSE banners hanging from the ceiling.",
    "source_url": "https://commons.wikimedia.org/wiki/File:Trading_floor_of_the_New_York_Stock_Exchange,_New_York_City_LCCN2011632435.tif",
    "author": "Carol M. Highsmith (Library of Congress, Prints and Photographs Division, LCCN 2011632435)",
    "license": "Public domain (Highsmith gift to the Library of Congress; LoC: \"No known restrictions on publication\")",
    "license_url": "https://commons.wikimedia.org/wiki/Template:PD-Highsmith",
    "is_original_diagram": false,
    "person_identified_by_source": null,
    "suggested_chapter": "2 Business model",
    "credit_line": "Photo: Carol M. Highsmith, Library of Congress (public domain)",
    "retrieved": "2026-09-26",
    "sha256": "d65235d8e978f8bd956a52d3c5d0f360a70c4e66b8b202b05a12702b4e668c5e",
    "notes": "Traders visible are not identified; do not describe any individual. LoC rights advisory read from loc.gov JSON record. Downloaded as 960px Commons thumbnail (portrait)."
  },
  {
    "id": "senate-hearing-2002-01-24",
    "file": "images/senate-hearing-2002-01-24.jpg",
    "title": "Senate Governmental Affairs Committee hearing on Enron, January 2002",
    "description": "Photo caption from the source (Senator Fred Thompson's office): Senator Thompson questions former SEC Chairman Arthur Levitt during the Governmental Affairs Committee's opening hearing into the Enron bankruptcy. Seated from left to right are Senators Susan Collins (R-ME), Senator Thompson, and Joe Lieberman (D-CT). Dated 2002-01-24 on Commons.",
    "alt": "Three senators seated at a hearing dais with microphones and name plates; the man in the center is speaking.",
    "source_url": "https://commons.wikimedia.org/wiki/File:Senator_Thompson_questions_former_SEC_Chairman_Arthur_Levitt_during_the_Governmental_Affairs_Committee%27s_opening_hearing_into_the_Enron_bankruptcy.jpg",
    "author": "Office of Senator Fred Thompson (archived at webarchive.loc.gov)",
    "license": "Public domain (work of the U.S. Congress)",
    "license_url": "https://commons.wikimedia.org/wiki/Template:PD-USGov-Congress",
    "is_original_diagram": false,
    "person_identified_by_source": true,
    "suggested_chapter": "4 Warning signs (alt: 7 Aftermath)",
    "credit_line": "Photo: Office of Sen. Fred Thompson, via Wikimedia Commons (public domain)",
    "retrieved": "2026-09-26",
    "sha256": "e99c5649dfd9b1b725d70a15c21f9f534a50afa822bfa22bf224ebae7d446e2e",
    "notes": "Only Collins, Thompson and Lieberman are named by the source; staff behind them are not identified. Levitt is not visible. The hearing date comes from the photo caption, not the library; writers should cite a library document for any claim about the hearing. Small original (510px wide); saved as 500px thumbnail, so display it no wider than ~500px."
  },
  {
    "id": "enron-downtown-2009",
    "file": "images/enron-downtown-2009.jpg",
    "title": "Enron's former buildings in downtown Houston, 2009",
    "description": "The curved sky bridge linking Enron's former office towers in downtown Houston, photographed in June 2009, after the company's collapse.",
    "alt": "A curved glass sky bridge crossing a downtown street between tall glass office buildings, with parked vans below.",
    "source_url": "https://commons.wikimedia.org/wiki/File:Enron_Downtown_Houston_TX_-_panoramio.jpg",
    "author": "Chanilim714 (Panoramio)",
    "license": "CC BY-SA 3.0",
    "license_url": "https://creativecommons.org/licenses/by-sa/3.0/",
    "is_original_diagram": false,
    "person_identified_by_source": null,
    "suggested_chapter": "5 Collapse",
    "credit_line": "Photo: Chanilim714, via Wikimedia Commons, CC BY-SA 3.0",
    "retrieved": "2026-09-26",
    "sha256": "4794931a066917b7d4a71ab87e0a8195526d8dbe80f3cb26929c1242880a800b",
    "notes": "Share-alike: if the site alters (e.g. crops) this photo, the altered version must also be CC BY-SA 3.0. License confirmed by Panoramio review bot on Commons (Oct 2016). Downloaded as 960px Commons thumbnail."
  },
  {
    "id": "supreme-court-building",
    "file": "images/supreme-court-building.jpg",
    "title": "U.S. Supreme Court Building, Washington, D.C.",
    "description": "The west front of the U.S. Supreme Court Building, photographed by Carol M. Highsmith (Library of Congress; dated 'between 1980 and 2006').",
    "alt": "The marble Supreme Court Building with its row of tall columns and triangular pediment against a deep blue sky.",
    "source_url": "https://commons.wikimedia.org/wiki/File:Supreme_Court_Building,_Washington,_D.C_LCCN2011632073.tif",
    "author": "Carol M. Highsmith (Library of Congress, Prints and Photographs Division, LCCN 2011632073)",
    "license": "Public domain (Highsmith gift to the Library of Congress; LoC: \"No known restrictions on publication\")",
    "license_url": "https://commons.wikimedia.org/wiki/Template:PD-Highsmith",
    "is_original_diagram": false,
    "person_identified_by_source": null,
    "suggested_chapter": "6 Arthur Andersen",
    "credit_line": "Photo: Carol M. Highsmith, Library of Congress (public domain)",
    "retrieved": "2026-09-26",
    "sha256": "d1d656f42d5c146f1f2fdb9bfd225bacaec76c53f9fb233141f7836c4efb3132",
    "notes": "No free, clearly identified photo of an Arthur Andersen office was found (see images-websites.md). Downloaded as 1280px Commons thumbnail of the LoC TIFF."
  },
  {
    "id": "sox-signing-oxley",
    "file": "images/sox-signing-oxley.jpg",
    "title": "Signing of the Sarbanes-Oxley Act, July 30, 2002",
    "description": "White House caption: President George W. Bush shakes hands with Congressman Mike Oxley, R-OH, during the signing ceremony of the Sarbanes-Oxley Act in the East Room, July 30 (2002). Photo by Eric Draper, White House Photo Office.",
    "alt": "President Bush shaking hands with Congressman Oxley in the White House East Room, with other men in suits nearby and a podium sign reading Corporate Responsibility.",
    "source_url": "https://commons.wikimedia.org/wiki/File:President_George_W._Bush_shakes_hands_with_Congressman_Mike_Oxley.jpg",
    "author": "Eric Draper, White House Photo Office (The Bush White House)",
    "license": "Public domain (work of the Executive Office of the President)",
    "license_url": "https://commons.wikimedia.org/wiki/Template:PD-USGov-POTUS",
    "is_original_diagram": false,
    "person_identified_by_source": true,
    "suggested_chapter": "7 Aftermath and reform",
    "credit_line": "White House photo by Eric Draper, via Wikimedia Commons (public domain)",
    "retrieved": "2026-09-26",
    "sha256": "9e9c8473f25b9e270c3225be946c4c6dec3e3c256223437accde9fcacfce6f6b",
    "notes": "Source identifies only Bush and Oxley; the other people are not named, so do not name them. The Commons caption also contains a Bush quotation; do not use it unless it is verified against a library document (e.g. the signing remarks in the library). The signing date must be cited to a library document in the text. Small original (515px); saved as 500px thumbnail. Original White House page: https://georgewbush-whitehouse.archives.gov/news/releases/2002/07/images/20020730_p20314-27a-ed-515h.html (not visited)."
  },
  {
    "id": "diagram-spe-basic",
    "file": "images/diagram-spe-basic.svg",
    "narrow_file": "images/diagram-spe-basic-narrow.svg",
    "title": "How a special purpose entity (SPE) works",
    "description": "Original diagram. Generic concept, not a specific Enron deal: a company moves an asset into a separate entity funded by outside lenders and investors, receives cash, and (if the rules treat the entity as truly independent) keeps the asset and the debt off its balance sheet.",
    "alt": "Diagram: the company sends an asset to a special purpose entity; outside investors and lenders fund the SPE; the SPE pays the company cash. A dashed box marks what stays on the company's balance sheet and what moves off it.",
    "source_url": null,
    "author": "Ask Why site team (Image Researcher & Diagrammer agent)",
    "license": "Original work for this site",
    "license_url": null,
    "is_original_diagram": true,
    "person_identified_by_source": null,
    "suggested_chapter": "3 Special purpose entities",
    "credit_line": "Diagram: Ask Why site team",
    "retrieved": "2026-09-26",
    "sha256": "ff984da0f0ce0f13a09a39493e1da651830a7e61cfed25f5e1fdffedd245b54a",
    "notes": "Wide version (800x560) for desktop/projector; narrow version (520x1010) for phones: use <picture><source media=\"(max-width: 600px)\" srcset=\"...-narrow.svg\">. Colors follow the OS light/dark setting when used as <img>; when inlined, the site can override with --diagram-bg, --diagram-ink, --diagram-muted. Each diagram carries its own background panel so it stays legible if the manual theme toggle disagrees with the OS setting."
  },
  {
    "id": "diagram-mark-to-market",
    "file": "images/diagram-mark-to-market.svg",
    "narrow_file": "images/diagram-mark-to-market-narrow.svg",
    "title": "Illustration: waiting for the cash vs. mark-to-market",
    "description": "Original illustration with made-up numbers: a 10-year contract expected to earn $10 a year. Reporting profit as the cash is earned shows $10 each year; mark-to-market reports about $70 (the estimated present value of all ten years) in year 1 and only small updates afterwards. The cash received is the same either way.",
    "alt": "Two bar charts. Top: ten equal blue bars of $10, one per year. Bottom: one tall orange bar of about $70 in year 1, then nine tiny bars. Marked ILLUSTRATION.",
    "source_url": null,
    "author": "Ask Why site team (Image Researcher & Diagrammer agent)",
    "license": "Original work for this site",
    "license_url": null,
    "is_original_diagram": true,
    "person_identified_by_source": null,
    "suggested_chapter": "2 Business model and mark-to-market",
    "credit_line": "Illustration: Ask Why site team (made-up numbers)",
    "retrieved": "2026-09-26",
    "sha256": "284d9f38c4616a40a97aab5dd77349f3cae8af5d6241d2767854ecf169f1c1f9",
    "notes": "'About $70' = $10 a year for 10 years discounted at roughly 7% a year (present value ~ $70.24); the discount rate is not shown, to keep it simple. Same wide/narrow and theming notes as diagram-spe-basic."
  },
  {
    "id": "diagram-raptor",
    "file": "images/diagram-raptor.svg",
    "narrow_file": "images/diagram-raptor-narrow.svg",
    "title": "How the Raptor \"hedges\" worked (2000–2001)",
    "description": "Original diagram of Enron-specific facts from checked fact cards. Enron put its own stock (and rights to more) into the four Raptor SPEs; LJM2, managed by CFO Andrew Fastow, put $30 million into each and got $39.5–41 million back from each within six months; the Raptors promised to cover losses on Enron's merchant investments. Because the Raptors' main asset was Enron stock, the protection failed as Enron's share price fell: the Dec. 2000 cross-guarantee, the March 2001 restructuring ($504 million shortfall), and the Sept. 2001 termination with a charge of about $710 million before taxes.",
    "alt": "Flow diagram: Enron sends its stock to the four Raptors; LJM2 puts in $30 million each and takes $39.5–41 million back from each; the Raptors promise to cover Enron's investment losses. A panel shows the chain: Enron's share price falls, the Raptors' Enron stock is worth less, they cannot pay, Enron faces the losses. Timeline: Dec. 22, 2000; Mar. 26, 2001; Sept. 28, 2001.",
    "source_url": null,
    "author": "Ask Why site team (Image Researcher & Diagrammer agent)",
    "license": "Original work for this site",
    "license_url": null,
    "is_original_diagram": true,
    "person_identified_by_source": null,
    "suggested_chapter": "3 Special purpose entities",
    "credit_line": "Diagram: Ask Why site team. Sources: Powers Report; Enron Form 10-Q, Q3 2001",
    "retrieved": "2026-09-26",
    "sha256": "b8896285cb2ec071e427f568149838c19fcae7eb9b24f873c560b15ad6c35521",
    "narrow_sha256": "9e3966d8830916e49813354ba4ae98eb8bb92e851ff2f2403a18ed5224c01f27",
    "fact_cards": [
      "A-021",
      "A-041",
      "A-042",
      "A-051",
      "A-052",
      "A-053",
      "A-055",
      "A-056",
      "A-057",
      "A-058",
      "fn-06",
      "fn-08",
      "fn-18"
    ],
    "notes": "Numbers shown: Raptor I contribution ~$537M stock/contracts + $50M note (A-052); $30M per Raptor and $39.5–41M returned within six months (A-053 claim and notes: $41M, $41M, $39.5M, $40.5M); $532M = more than 80% of $650M pre-tax, Q3–Q4 2000 (A-055); $504M shortfall and >$800M contracts (A-057); ~$35M to LJM2 and ~$710M pre-tax charge (A-058). Per factcheck-round1 ruling 3, only the undisputed $710M pre-tax figure is shown (no after-tax figure). Quote 'In effect, Enron was hedging risk with itself.' is verbatim from A-051 (Powers p. 97). Raptor III/New Power footnote from A-051 notes. 'Managed by Fastow' rests on A-041 (board approved Fastow's role in LJM2) and A-042 (PPM named Fastow, Kopper and Glisan as managers). Wide version for desktop/projector; narrow version for phones: use <picture><source media=\"(max-width: 600px)\" srcset=\"...-narrow.svg\">. Same light/dark theming as diagram-spe-basic (--diagram-bg, --diagram-ink, --diagram-muted overrides when inlined). Source line is inside the SVG."
  },
  {
    "id": "diagram-chewco-ljm",
    "file": "images/diagram-chewco-ljm.svg",
    "narrow_file": "images/diagram-chewco-ljm-narrow.svg",
    "title": "Who was who: Enron's related entities",
    "description": "Original diagram of Enron-specific facts from checked fact cards. Seven boxes: Enron; JEDI (1993, Enron and CalPERS, $250M each) and Chewco (1997, run by Michael Kopper, who reported to Fastow; Enron guaranteed its $240M bank loan); LJM1 (June 1999, Fastow general partner) and its Swap Sub (Rhythms hedge); LJM2 (October 1999, managed by Fastow; about 50 investors, $394M committed) and the four Raptors ($30M each from LJM2). JEDI, Chewco and Swap Sub are marked as the entities Enron said on Nov. 8, 2001 should have been consolidated.",
    "alt": "Tree diagram: Enron at the top with three branches. Branch 1 (1993–1997): JEDI, and Chewco, which bought CalPERS's half of JEDI. Branch 2 (1999): LJM1, which set up Swap Sub. Branch 3 (1999–2001): LJM2, which put $30 million into each of four Raptors. JEDI, Chewco and Swap Sub carry a RESTATED tag.",
    "source_url": null,
    "author": "Ask Why site team (Image Researcher & Diagrammer agent)",
    "license": "Original work for this site",
    "license_url": null,
    "is_original_diagram": true,
    "person_identified_by_source": null,
    "suggested_chapter": "3 Special purpose entities",
    "credit_line": "Diagram: Ask Why site team. Sources: Powers Report; Enron Form 8-K, Nov. 8, 2001",
    "retrieved": "2026-09-26",
    "sha256": "722a226bd2895b505082dd28b83e3caa48fe1d42e1c416f0d4ba958717572f21",
    "narrow_sha256": "c77ace35382585a0e104f23bcef65675158b57704613931ce7d284f5a54b035f",
    "fact_cards": [
      "A-031",
      "A-032",
      "A-033",
      "A-034",
      "A-040",
      "A-041",
      "A-042",
      "A-046",
      "A-048",
      "A-051",
      "A-052",
      "A-053",
      "A-060",
      "A-083"
    ],
    "notes": "LJM2 approval shown only as 'October 1999' per factcheck-round1 ruling 5 (Oct 11 vs Oct 12 disputed). Kopper's Southampton loan amount (disputed, ruling 13) is not shown. 'Nearly all its $11.5M equity was borrowed' = A-034 ($11.4M of $11.5M from Barclays loans documented as equity). 'Board was not told of Kopper's role' = A-033 (committee saw no evidence it was disclosed to Lay or the board). RESTATED tags: A-083 (Chewco, JEDI and an LJM1 subsidiary) and A-048 (that subsidiary is Swap Sub). Enrichment figures from A-060. Wide version for desktop/projector; narrow version for phones: use <picture><source media=\"(max-width: 600px)\" srcset=\"...-narrow.svg\">. Same light/dark theming as diagram-spe-basic (--diagram-bg, --diagram-ink, --diagram-muted overrides when inlined). Source line is inside the SVG."
  },
  {
    "id": "chart-restatement",
    "file": "images/chart-restatement.svg",
    "narrow_file": "images/chart-restatement-narrow.svg",
    "title": "How much Enron's restatement cut reported net income, 1997–2000",
    "description": "Original bar chart of Enron-specific figures. Reduction to reported net income as restated in Enron's Q3 2001 Form 10-Q (filed Nov. 19, 2001): $79M (1997: $105M reported, $26M restated), $139M (1998: $703M to $564M), $258M (1999: $893M to $635M), $137M (2000: $979M to $842M). A note gives the different figures in the Nov. 8, 2001 8-K press release ($96M, $113M, $250M, $132M) and the Powers Report ($28M, $133M, $248M, $99M; Chewco and LJM1 only, without audit adjustments).",
    "alt": "Bar chart of four years. 1997: minus $79 million. 1998: minus $139 million. 1999: minus $258 million, the largest. 2000: minus $137 million. Each bar is labeled with its value and the reported and restated net income. A box below lists the different figures from the Nov. 8, 2001 announcement and the Powers Report.",
    "source_url": null,
    "author": "Ask Why site team (Image Researcher & Diagrammer agent)",
    "license": "Original work for this site",
    "license_url": null,
    "is_original_diagram": true,
    "person_identified_by_source": null,
    "suggested_chapter": "5 The collapse",
    "credit_line": "Chart: Ask Why site team. Data: Enron Form 10-Q, Q3 2001",
    "retrieved": "2026-09-26",
    "sha256": "d6a0afd8b76a3a5db1a92a595b82f5c9e18446708af1d92028fca496e460ee6e",
    "narrow_sha256": "7c4dfdc63e2361023017a2ae6140d125ca779264b6a8a53ab3609bec414ab06d",
    "fact_cards": [
      "A-083",
      "A-084",
      "A-085",
      "A-086",
      "A-039"
    ],
    "notes": "Uses the 10-Q figures, as the Fact-Checker ruled (factcheck-round1 ruling 1). Bar values are reported minus restated net income from A-085 (claim: 105/26, 703/564, 893/635, 979/842); they match the reductions listed in A-085's notes (79/139/258/137), and I re-read the 10-Q table (lines 985-1062, printed p. 15) to confirm. 'The cuts came from JEDI, Chewco, an LJM1 subsidiary, plus audit adjustments' = 10-Q components in A-085 notes. 8-K figures from A-084; Powers figures from A-086 (A-039 gives the Chewco-only component). Wide version is vertical bars; phone version uses horizontal bars so labels fit. Numbers are printed as labels, not only bar heights. Wide version for desktop/projector; narrow version for phones: use <picture><source media=\"(max-width: 600px)\" srcset=\"...-narrow.svg\">. Same light/dark theming as diagram-spe-basic (--diagram-bg, --diagram-ink, --diagram-muted overrides when inlined). Source line is inside the SVG."
  },
  {
    "id": "diagram-prepay",
    "file": "images/diagram-prepay.svg",
    "narrow_file": "images/diagram-prepay-narrow.svg",
    "title": "How a bank \"prepay\" worked",
    "description": "Original diagram of a simplified JPMorgan Chase prepay, from checked bank cards. The bank sends cash to an offshore entity (Mahonia), which pays Enron now as a 'prepayment'; Enron makes commodity deliveries later, which pass back to the bank; an offsetting swap sends the price risk back to Enron. Net effect: cash now, repaid later with interest set in advance (the SEC alleged the prepays were 'in substance loans'). Panels show how Enron could record it (cash flow from operations, not debt; loans on its tax returns) and the Senate staff's estimate for end-2000 if booked as debt. A footnote records the dispute over who controlled Mahonia.",
    "alt": "Triangle diagram: the bank sends cash to an offshore entity, Mahonia, which sends cash to Enron; Enron's commodity deliveries go back through Mahonia to the bank; an offsetting swap arrow runs from the bank to Enron. Below: panels on how Enron could record the deal and what the numbers would have looked like as debt, two short quotes, and a footnote on the disputed control of Mahonia.",
    "source_url": null,
    "author": "Ask Why site team (Image Researcher & Diagrammer agent)",
    "license": "Original work for this site",
    "license_url": null,
    "is_original_diagram": true,
    "person_identified_by_source": null,
    "suggested_chapter": "Phase 2: The Banks page (alt: Ch. 5 or Follow the Money lens)",
    "credit_line": "Diagram: Ask Why site team. Sources: Senate PSI hearing (July 23, 2002); SEC; bankruptcy examiner",
    "retrieved": "2026-09-27",
    "sha256": "097e0d6dc0c22aa3239532234ca5fb6b07f39e0c40857d9bef063654d0f9263a",
    "narrow_sha256": "4111be3826aad894f547993f15cdc1e41e7513506740dd204338622eb6ec053c",
    "fact_cards": [
      "K-001",
      "K-002",
      "K-003",
      "K-004",
      "K-005",
      "K-006",
      "K-009",
      "K-010",
      "K-014",
      "K-016",
      "K-045"
    ],
    "notes": "Flow (steps 1-4) from Roach's sworn 'simplified version' (K-002); swap and 'in substance loans' from the SEC's allegations against JPMorgan Chase (K-014: risk passed from Enron to a Chase-sponsored entity, to Chase, and back to Enron). Recording: cash flow from operations (K-001), 'price risk management liabilities,' 'minority interest,' or otherwise (K-016, SEC alleged), loans on tax returns (K-005). End-2000 estimate labeled as Senate staff estimate (K-006). Citigroup total shown as $4.7-4.8B per fact-check point 4 (K-004). Quotes verbatim: 'what remains is a loan to Enron' (K-001, re-read at hrg-psi-banks-v1 text lines 2019-2021, printed p. 14); 'prepaid forwards are fundamentally different than funded debt' (K-009 notes, verified by checker, PDF 81). Mahonia labeled neutrally as 'Offshore entity (Mahonia)' per brief; footnote gives all three positions with attribution (K-002 Roach, K-010 Dellapina, K-045 examiner). Levin's Exhibit 118 reading (names East Moss, not Mahonia) not shown. Wide 800 px, narrow 520 px; same theming as other diagrams. Four tests (K-003) support the 'dressed up as trades' framing in the title/desc only."
  }
];
